'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const file=path.join(__dirname,'../ui/reading.js');
assert.ok(fs.existsSync(file),'Reading module must exist');
const source=fs.readFileSync(file,'utf8');
const context={console,setTimeout,clearTimeout,state:{workspace:'one',data:{documents:[],notes:[]}},document:{addEventListener(){}},escapeHTML:value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),sourceLabel:d=>d.name};
vm.createContext(context);vm.runInContext(source,context);
const words=[{index:0,text:'Keep',rect:[0.1,0.2,0.2,0.24],block:0,line:0},{index:1,text:'these',rect:[0.22,0.2,0.35,0.24],block:0,line:0},{index:2,text:'words',rect:[0.1,0.25,0.24,0.29],block:0,line:1}];
const original=JSON.stringify(words);
assert.deepEqual(JSON.parse(JSON.stringify(context.readingSelectionFromWords(words,0,2))),{quote:'Keep these\nwords',word_start:0,word_end:2,rects:[[0.1,0.2,0.2,0.24],[0.22,0.2,0.35,0.24],[0.1,0.25,0.24,0.29]]});
assert.equal(context.readingSelectionFromWords(words,2,0).quote,'Keep these\nwords','Reverse selection has identical quote');
assert.equal(JSON.stringify(words),original,'Geometry remains immutable');
assert.throws(()=>context.readingSelectionFromWords(words,0,9),'Invalid word selection cannot be saved');
assert.equal(context.readingCitedBody({document_id:'a'.repeat(32),page:2,quote:'Keep\nwords',comment:'My thought'}),'[[source:'+ 'a'.repeat(32)+':2]]\n\n> Keep\n> words\n\nMy thought\n');
assert.throws(()=>context.readingCitedBody({document_id:'bad',page:2,quote:'quote',comment:''}),'Invalid immutable locator rejected');
const docs=[{id:'a',workspace_id:'one',reading:{status:'reading',favorite:true,tags:['HPB'],collection:'Review'}},{id:'b',workspace_id:'one',reading:{status:'unread',favorite:false,tags:[],collection:''}},{id:'c',workspace_id:'two',reading:{status:'reading',favorite:true,tags:['HPB'],collection:'Review'}}];
const copy=JSON.stringify(docs);
assert.deepEqual(Array.from(context.readingFilterDocuments(docs,{status:'reading',favorite:true,tag:'hpb',collection:'Review'}),d=>d.id),['a']);
assert.deepEqual(Array.from(context.readingFilterDocuments(docs,{status:'all',favorite:false,tag:'',collection:''}),d=>d.id),['a','b']);
assert.equal(JSON.stringify(docs),copy);
assert.deepEqual(Array.from(context.readingIndicesForQuote(words,'Keep these\nwords')),[0,1,2]);
assert.throws(()=>context.readingIndicesForQuote(words,'eep these'),'Partial words cannot imply full highlight');
assert.throws(()=>context.readingIndicesForQuote([...words,{index:3,text:'Keep',rect:[0,0,0.1,0.1]}],'Keep'),'Repeated passages require exact page selection');
assert.equal(context.readingRequestCurrent({workspace:'one',document:'a',page:2,generation:5},{workspace:'one',document:'a',page:2,generation:6}),false,'Stale generation rejected');
assert.equal(context.readingRequestCurrent({workspace:'one',document:'a',page:2,generation:5},{workspace:'one',document:'a',page:2,generation:5}),true);
assert.ok(!source.includes('MutationObserver'),'Integration must use explicit hooks');
async function readingAsyncChecks(){
 context.$=()=>null;context.$$=()=>[];const app=context.KoshReading=vm.runInContext('KoshReading',context);let version=0,calls=[],inFlight=0;
 const snapshot=()=>({schema_version:1,version,sources:[],resume:{document_id:null,page:1,next_action:''},annotations:[],claims:[]});
 context.request=async(route,body)=>{if(body){calls.push({route,body});assert.equal(body.expected_version,version);assert.equal(inFlight,0,'Workspace mutations must serialize');inFlight++;await new Promise(resolve=>setTimeout(resolve,2));version++;inFlight--;return snapshot();}return snapshot();};
 await app.load();await Promise.all([app.mutate('/reading/source',{document_id:'a',favorite:true}),app.mutate('/reading/claim',{id:'b',status:'attached'})]);
 assert.deepEqual(calls.map(call=>call.body.expected_version),[0,1]);assert.equal(app.current().version,2);
 let releaseGet;context.request=async(route,body)=>{if(!body){const old=snapshot();await new Promise(resolve=>{releaseGet=resolve;});return old;}assert.equal(body.expected_version,version);version++;return snapshot();};
 const oldGet=app.load(true);await app.mutate('/reading/source',{favorite:false});releaseGet();assert.equal((await oldGet).version,3,'A stale GET must return latest cache after a concurrent successful mutation');assert.equal(app.current().version,3);
 context.request=async()=>snapshot();
 context.state.workspace='two';assert.equal(app.current(),null,'Old workspace data cannot appear in current()');await app.load();
 let refused=false;context.request=async(route,body)=>{if(body&&!refused){refused=true;version++;const error=new Error('stale');error.status=409;throw error;}return snapshot();};
 await assert.rejects(app.mutate('/reading/source',{favorite:true}),/fields are retained/);assert.equal(app.current().version,4,'Conflict refetches latest version');
 const queued=app.mutate('/reading/source',{favorite:false});context.state.workspace='three';app.current();await assert.rejects(queued,/Workspace changed/,'Queued write cannot cross workspace boundary');
 context.state.workspace='one';context.state.doc={id:'doc'};context.state.page=2;const storage=new Map();context.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)};
 const draft=context.readingDraft();draft.quote='Keep words';draft.comment='Unsaved comment';context.readingPreserveDraft();context.state.workspace='two';context.readingResetWorkspace();context.state.workspace='one';context.readingResetWorkspace();assert.equal(context.readingDraft().comment,'Unsaved comment','Workspace switching preserves pending capture');
 assert.ok([...storage.values()].some(value=>value.includes('Unsaved comment')),'Recovery stores pending capture');
 console.log('Reading UI: selection, citations, filters, serialized mutations, conflict reload, workspace isolation and recovery passed');
}
async function openDocumentChecks(){
 const app=fs.readFileSync(path.join(__dirname,'../ui/app.js'),'utf8');const start=app.indexOf('async function openDocument('),end=app.indexOf('\nfunction activeEditor(',start);assert.ok(start>=0&&end>start,'openDocument is required');
 let loads=0;const ctx={innerWidth:1000,flushEdits:async()=>true,setPanelOpen(){},$:()=>({innerHTML:''}),request:async()=>({document:{id:'d',kind:'pdf',pages:6}}),KoshReading:{load:async()=>{loads++;}},readingSource:()=>({last_page:4}),render(){},renderMain(){},notify(){},selectedPassage:null,Number,Math,state:{readSequence:0,workspace:'one',askScope:'workspace'}};
 vm.createContext(ctx);vm.runInContext(app.slice(start,end),ctx);
 await ctx.openDocument('d');assert.equal(ctx.state.page,4,'A plain open returns to the remembered page');assert.equal(loads,1,'Remembered page is read from loaded reading state');
 await ctx.openDocument('d',2);assert.equal(ctx.state.page,2,'An explicit page wins');
 await ctx.openDocument('d',1);assert.equal(ctx.state.page,1,'Explicit page 1 is not replaced');assert.equal(loads,1);
 await ctx.openDocument('d',9);assert.equal(ctx.state.page,6,'Pages stay within the document');
 console.log('Reading UI: plain open keeps the remembered page');
}
readingAsyncChecks().then(openDocumentChecks).catch(error=>{console.error(error);process.exitCode=1;});
