'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const storage=new Map(),listeners={};
const context={console,document:{addEventListener(name,fn){listeners[name]=fn;},querySelector(){return null;}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},state:{workspace:'w',note:'n',data:{notes:[]},editors:new Map()},setTimeout,URL:{},Blob};
Object.defineProperty(context.localStorage,'length',{get:()=>storage.size});context.localStorage.key=index=>Array.from(storage.keys())[index]||null;
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../ui/reviewer.js'),'utf8'),context);
const api=vm.runInContext('KoshReviewer',context);
const note={id:'n',workspace_id:'w',body:'🟦 Blue widgets. Blue widgets.',version:3};
const linked=api.anchor(note,'Blue widgets.',1);
assert.equal(linked.passage_start,16);assert.equal(linked.passage_end,29);assert.equal(linked.note_version,3);
assert.equal(api.anchor(note,'Blue widgets.',0).passage_start,2);
assert.throws(()=>api.anchor(note,'Blue widget.'),/exact/i);
assert.throws(()=>api.anchor(note,'Blue widgets.',2),/occurrence/i);
assert.equal(api.occurrences(note.body,'Blue widgets.').length,2);
assert.equal(api.occurrences('aaa','aa').length,2,'Overlapping occurrences have distinct exact offsets');
assert.throws(()=>api.anchor(note,''),/passage/i);
const row={...linked,id:'r',reviewer:'R',comment:'Explain',planned_text:'Plan',revised_text:'',response:'',status:'open',archived:false,stale:false,history:[]};
const draft=api.makeDraft(row,4);draft.comment='My edit';
assert.equal(row.comment,'Explain','Pending fields never mutate saved records');
assert.throws(()=>api.assertScope(draft,'other'),/workspace/i);
assert.equal(api.assertScope(draft,'w'),true);
assert.equal(api.recordState(row,{...note,dirty:true}).stale,true);
assert.equal(api.recordState(row,note).stale,false);
api.retain('w:r',draft);assert.equal(JSON.parse(storage.get('kosh-reviewer:w:r')).comment,'My edit');
const recovered=api.recover('w:r');assert.equal(recovered.comment,'My edit');assert.equal(recovered.expected_version,4);
storage.set('kosh-reviewer:bad','{broken');assert.equal(api.recover('bad'),null);
console.log('Reviewer helpers: Unicode/repeated exact passage, saved-state isolation, workspace and recovery guards passed.');

function element(){return {dataset:{},value:'',innerHTML:'',textContent:'',disabled:false,checked:false,open:false,isConnected:true,listeners:{},addEventListener(name,fn){this.listeners[name]=fn;},querySelectorAll(){return [];},focus(){if(!this.disabled){this.focused=true;context.document.activeElement=this;}},showModal(){this.open=true;},close(){this.open=false;},setAttribute(k,v){this[k]=v;},click(){},remove(){}};}
const elements=new Map();
for(const id of ['reviewer-dialog','rv-form','rv-list','rv-history','rv-error','rv-message','rv-note','rv-reviewer','rv-comment','rv-passage','rv-occurrence','rv-planned-text','rv-revised-text','rv-response','rv-status','rv-anchor','rv-show-archived','rv-export-archived','rv-export-choice','rv-current-saved','rv-letter-title'])elements.set('#'+id,element());
let mounted=false;
context.document.querySelector=selector=>selector==='#reviewer-dialog'&&!mounted?null:elements.get(selector)||null;
context.document.createElement=tag=>tag==='dialog'?elements.get('#reviewer-dialog'):element();
context.document.body={append(value){if(value===elements.get('#reviewer-dialog'))mounted=true;}};
elements.get('#reviewer-dialog').querySelector=selector=>selector==='.rv-export'?{insertAdjacentHTML(){},querySelector:()=>elements.get('#rv-export-choice')}:null;
elements.get('#reviewer-dialog').querySelectorAll=()=>Array.from(elements.entries()).filter(([id])=>!['#rv-form','#reviewer-dialog','#rv-list','#rv-history','#rv-error','#rv-message','#rv-anchor','#rv-current-saved'].includes(id)).map(([,value])=>value);
elements.get('#rv-list').contains=value=>!!value?.dataset.rvId;
context.state.data.notes=[note];context.state.editors.set('n',{...note,dirty:false,conflict:false});
let response={workspace_id:'w',version:4,comments:[row]},fail=false,payload=null;
context.request=async(route,body)=>{if(body){payload=body;if(fail){const error=new Error('Changed elsewhere');error.status=409;throw error;}response={workspace_id:'w',version:5,comments:[{...row,comment:body.comment||row.comment}]};}return response;};
context.notify=()=>{};context.activeEditor=()=>context.state.editors.get('n');
(async()=>{
 await api.open();assert.equal(context.document.activeElement,elements.get('#rv-reviewer'),'Opening focuses the enabled reviewer field');api.edit('r');elements.get('#rv-comment').value='Retained comment';api.capture();
 fail=true;await api.save();assert.match(elements.get('#rv-error').textContent,/Changed elsewhere/);
 assert.equal(elements.get('#rv-comment').value,'Retained comment');
 assert.equal(JSON.parse(storage.get('kosh-reviewer:w:r')).comment,'Retained comment');
fail=false;await api.save();assert.equal(payload.expected_version,4);assert.equal(payload.comment,'Retained comment');
 assert.equal(context.document.activeElement,elements.get('#rv-message'),'Successful save moves focus to its confirmation');
 assert.equal(context.state.data.notes[0].body,note.body,'Reviewer saves never edit manuscript');
 api.newComment();elements.get('#rv-passage').value='Blue widgets.';elements.get('#rv-occurrence').value='1';api.capture();api.link();
 assert.equal(api.currentDraft().passage_start,16);
 context.state.editors.get('n').dirty=true;assert.throws(()=>api.link(),/Save.*manuscript/i);
 context.state.editors.get('n').dirty=false;
 context.state.workspace='other';await api.save();assert.match(elements.get('#rv-error').textContent,/workspace/i);
 assert.equal(api.currentDraft().passage_start,16,'Workspace error retains the pending passage');
 context.state.workspace='w';elements.get('#rv-comment').value='One new response';api.capture();
 let finish;context.request=async(route,body)=>{if(body){payload=body;return new Promise(resolve=>finish=resolve);}return response;};
 const pending=api.save();await Promise.resolve();
 let cancelled=false;elements.get('#reviewer-dialog').listeners.cancel({preventDefault(){cancelled=true;}});
 assert.equal(cancelled,true,'Escape must not close the dialog during a pending save');
 elements.get('#reviewer-dialog').close();context.state.workspace='other';context.state.data.notes.push({...note,id:'other-note',workspace_id:'other'});response={workspace_id:'other',version:0,comments:[]};await api.open();
 finish({workspace_id:'w',version:6,comments:[row,{...row,id:'new-record',comment:'One new response'}]});await pending;
 assert.equal(storage.has('kosh-reviewer:w:new'),false,'A late successful save clears the exact old pending new-comment recovery even after a forced reopen');
 assert.equal(api.pendingCount(),0,'Clean saved record and untouched other-workspace new form do not count as pending');
 const cleanRecovery=api.makeDraft(row,6,'w'),dirtyRecovery=api.makeDraft(row,6,'w');dirtyRecovery.response='Unsaved independent response';
 storage.set('kosh-reviewer:clean-recovery',JSON.stringify(cleanRecovery));storage.set('kosh-reviewer:dirty-recovery',JSON.stringify(dirtyRecovery));
 assert.equal(api.pendingCount(),1,'Storage-only recovery counts changed response fields and excludes an unchanged saved record');
 storage.delete('kosh-reviewer:clean-recovery');storage.delete('kosh-reviewer:dirty-recovery');
 context.state.workspace='w';elements.get('#reviewer-dialog').close();response={workspace_id:'w',version:6,comments:[row]};context.request=async(route,body)=>{if(route==='/reviewer/export'){payload=body;return {filename:'response.txt',content:'Saved response'};}return response;};context.URL={createObjectURL(){return 'blob:fixture';},revokeObjectURL(){}};context.setTimeout=()=>{};await api.open();
 elements.get('#rv-show-archived').checked=true;elements.get('#rv-export-archived').checked=false;
 const exportButton=element();exportButton.dataset.rvAction='export';const exportEvent={target:{closest:()=>exportButton},preventDefault(){}};
 await elements.get('#reviewer-dialog').listeners.click(exportEvent);assert.equal(payload.include_archived,false,'List archive visibility does not include archived comments in exports');
 elements.get('#rv-export-archived').checked=true;await elements.get('#reviewer-dialog').listeners.click(exportEvent);assert.equal(payload.include_archived,true);
 const oldEdit=element(),newEdit=element();oldEdit.dataset={rvId:'r',rvAction:'edit'};newEdit.dataset={rvId:'r',rvAction:'edit'};elements.set('[data-rv-action="edit"][data-rv-id="r"]',newEdit);context.document.activeElement=oldEdit;api.edit('r');assert.equal(context.document.activeElement,newEdit,'Selecting a record restores focus to its replacement control');
 const archiveButton=element();archiveButton.dataset={rvId:'r',rvAction:'archive'};elements.set('[data-rv-action="archive"][data-rv-id="r"]',archiveButton);context.request=async()=>({...response,version:7,comments:[{...row,archived:true}]});elements.get('#rv-show-archived').checked=true;
 await elements.get('#reviewer-dialog').listeners.click({target:{closest:()=>archiveButton},preventDefault(){}});assert.equal(context.document.activeElement,archiveButton,'Archive action restores focus after re-enabling controls');
 console.log('Reviewer mounted UI: failed-write retention, exact save version, relink, dirty draft and scope guards passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
