'use strict';

// Explicit mounts are called by app.js; original sources are never rewritten.
const readingModel={workspace:null,data:null,load:null,generation:0,epoch:0,queue:Promise.resolve(),listeners:new Set(),filter:{status:'all',favorite:false,tag:'',collection:''},geometry:null,pageGeneration:0,pendingJump:null,drafts:new Map(),placeDrafts:new Map(),annotationEdits:new Map(),showArchived:false,busy:false,progressTimer:null};
const readingStatuses=[['unread','Unread'],['reading','Reading'],['read','Read']];
function readingRequestCurrent(target,current){return target.workspace===current.workspace&&target.document===current.document&&target.page===current.page&&target.generation===current.generation;}
function readingSelectionFromWords(words,start,end){
 const low=Math.min(start,end),high=Math.max(start,end),chosen=words.filter(w=>w.index>=low&&w.index<=high);
 if(!Number.isInteger(low)||!Number.isInteger(high)||!chosen.length||chosen[0].index!==low||chosen[chosen.length-1].index!==high)throw new Error('Select a contiguous passage on this page.');
 let quote='';for(let i=0;i<chosen.length;i++){const word=chosen[i],previous=chosen[i-1];quote+=(i?(word.line!==undefined&&previous.line!==undefined&&(word.line!==previous.line||word.block!==previous.block)?'\n':' '):'')+word.text;}
 return {quote,word_start:low,word_end:high,rects:chosen.map(w=>w.rect.slice())};
}
function readingCitedBody(annotation){
 if(!/^[a-f0-9]{32}$/.test(annotation.document_id)||!Number.isInteger(annotation.page)||annotation.page<1)throw new Error('The saved passage has an invalid source locator.');
 return '[[source:'+annotation.document_id+':'+annotation.page+']]\n\n> '+String(annotation.quote).replace(/\n/g,'\n> ')+'\n\n'+(annotation.comment?annotation.comment+'\n':'');
}
function readingSource(id){return readingModel.data?.sources.find(s=>s.document_id===id)||{document_id:id,status:'unread',favorite:false,tags:[],collection:'',last_page:1};}
function readingFiltersActive(){const filter=readingModel.filter;return filter.status!=='all'||filter.favorite||filter.tag.trim()||filter.collection.trim();}
function readingIndicesForQuote(words,quote){const chosen=String(quote).trim().split(/\s+/),matches=[];for(let start=0;start<=words.length-chosen.length;start++){if(chosen.every((text,index)=>words[start+index].text===text))matches.push(words.slice(start,start+chosen.length).map(word=>word.index));}if(matches.length!==1)throw new Error(matches.length?'This quote occurs more than once on this PDF page. Select it on the page image for an exact highlight.':'This selected text does not match complete PDF words. Select complete words on the page image.');return matches[0];}
function readingFilterDocuments(items,options=readingModel.filter){
 const fold=value=>String(value||'').normalize('NFD').replace(/([\p{Script=Latin}\p{Script=Greek}\p{Script=Cyrillic}])\p{M}+/gu,'$1').toLowerCase();
 return items.filter(doc=>{const reading=doc.reading||readingSource(doc.id);return doc.workspace_id===state.workspace&&(options.status==='all'||reading.status===options.status)&&(!options.favorite||reading.favorite)&&( !options.tag||reading.tags.some(tag=>fold(tag)===fold(options.tag)))&&(!options.collection||fold(reading.collection)===fold(options.collection));});
}
function readingResetWorkspace(){
 if(readingModel.workspace===state.workspace)return;
 readingModel.workspace=state.workspace;readingModel.data=null;readingModel.load=null;readingModel.generation++;readingModel.epoch++;readingModel.pageGeneration++;readingModel.geometry=null;readingModel.pendingJump=null;readingModel.showArchived=false;readingModel.filter={status:'all',favorite:false,tag:'',collection:''};clearTimeout(readingModel.progressTimer);
}
function readingPublish(data){if(readingModel.data&&readingModel.data.version>data.version)return;readingModel.data=data;for(const callback of readingModel.listeners){try{callback(data);}catch(error){notify('Reading records loaded, but a view could not refresh: '+error.message,true,true);}}readingUpdateLibrary();readingRenderAnnotations();}
const KoshReading={
 current(){readingResetWorkspace();return readingModel.data;},
 onChange(callback){readingModel.listeners.add(callback);return ()=>readingModel.listeners.delete(callback);},
 async load(force=false){
  readingResetWorkspace();if(!state.workspace)return null;if(readingModel.data&&!force)return readingModel.data;if(readingModel.load&&!force)return readingModel.load;
  const workspace=state.workspace,generation=++readingModel.generation;
  const pending=request('/reading?workspace_id='+encodeURIComponent(workspace)).then(data=>{if(workspace!==state.workspace||generation!==readingModel.generation)throw new Error('Workspace changed before reading state loaded.');readingPublish(data);return readingModel.data;}).finally(()=>{if(readingModel.load===pending)readingModel.load=null;});
  readingModel.load=pending;return pending;
 },
 mutate(route,body){
  readingResetWorkspace();const workspace=state.workspace,epoch=readingModel.epoch;
  const operation=async()=>{if(workspace!==state.workspace||epoch!==readingModel.epoch)throw new Error('Workspace changed. Your unsaved fields were retained.');const current=await KoshReading.load();if(workspace!==state.workspace||epoch!==readingModel.epoch)throw new Error('Workspace changed. Your unsaved fields were retained.');try{const result=await request(route,{...body,workspace_id:workspace,expected_version:current.version});if(workspace===state.workspace&&epoch===readingModel.epoch)readingPublish(result);return result;}catch(error){if(error.status===409&&workspace===state.workspace&&epoch===readingModel.epoch){await KoshReading.load(true);throw new Error('Reading state changed in another window. Latest records loaded; your fields are retained. Review them and save again.');}throw error;}};
  const result=readingModel.queue.then(operation);readingModel.queue=result.catch(()=>{});return result;
 }
};
function readingDraftKey(documentId=state.doc?.id,page=state.page){return String(state.workspace)+':'+documentId+':'+page;}
function readingDraft(){
 const key=readingDraftKey();if(!readingModel.drafts.has(key)){let saved=null;try{saved=JSON.parse(localStorage.getItem('kosh-reading-draft:'+key)||'null');}catch{notify('Saved passage recovery could not be read. Existing storage was retained.',true,true);}
 readingModel.drafts.set(key,saved||{quote:'',comment:'',word_indices:null});}return readingModel.drafts.get(key);
}
function readingPlaceDraftKey(){return String(state.workspace)+':'+state.doc?.id;}
function readingPlaceDraft(){const key=readingPlaceDraftKey();if(!readingModel.placeDrafts.has(key)){let saved=null;try{saved=JSON.parse(localStorage.getItem('kosh-reading-place:'+key)||'null');}catch{notify('Reading-place recovery could not be read. Existing storage was retained.',true,true);}readingModel.placeDrafts.set(key,saved);}return readingModel.placeDrafts.get(key);}
function readingCapturePlaceForm(){
 if(!$('#reading-source-form')||!readingModel.data)return;const draft={status:$('#reading-source-status').value,favorite:$('#reading-source-favorite').checked,tags:$('#reading-source-tags').value,collection:$('#reading-source-collection').value,next_action:$('#reading-next-action').value};readingModel.placeDrafts.set(readingPlaceDraftKey(),draft);
 try{localStorage.setItem('kosh-reading-place:'+readingPlaceDraftKey(),JSON.stringify(draft));}catch{notify('Reading-place fields are kept in this window, but browser recovery could not be saved.',true,true);}
}
function readingPreserveDraft(){try{localStorage.setItem('kosh-reading-draft:'+readingDraftKey(),JSON.stringify(readingDraft()));return true;}catch{notify('Passage draft is kept in this window, but browser recovery could not be saved. Keep this window open until you save it.',true,true);return false;}}
function readingDiscardDraft(){readingModel.drafts.set(readingDraftKey(),{quote:'',comment:'',word_indices:null});try{localStorage.removeItem('kosh-reading-draft:'+readingDraftKey());}catch{notify('Saved capture succeeded, but its browser recovery could not be cleared.',true,true);}readingRenderCapture();}
function readingStatusOptions(value,all=false){return (all?[['all','All reading states'],...readingStatuses]:readingStatuses).map(([key,label])=>'<option value="'+key+'" '+(value===key?'selected':'')+'>'+label+'</option>').join('');}
function readingMountLibrary(){
 readingResetWorkspace();const target=$('.library-browse');if(!target||$('#reading-library-controls'))return;
 target.insertAdjacentHTML('beforeend','<div class="reading-library-controls" id="reading-library-controls"><label>Reading state<select id="reading-filter-status">'+readingStatusOptions(readingModel.filter.status,true)+'</select></label><label class="reading-favorite-filter"><input type="checkbox" id="reading-filter-favorite" '+(readingModel.filter.favorite?'checked':'')+'> Favorites</label><label>Tag<input type="search" id="reading-filter-tag" placeholder="Exact tag" value="'+escapeHTML(readingModel.filter.tag)+'"></label><label>Collection<input type="search" id="reading-filter-collection" placeholder="Collection name" value="'+escapeHTML(readingModel.filter.collection)+'"></label><button class="text-button" data-reading-action="clear-filters">Clear reading filters</button></div><p id="reading-library-message" class="small muted" role="status">Loading reading organization…</p><div id="reading-resume"></div><details class="reading-duplicate-review"><summary>Review possible duplicate sources</summary><p class="muted small">Compare sources with matching titles or DOI. Originals and their citation IDs stay separate.</p><button class="button" data-reading-action="duplicates">Find review candidates</button><div id="reading-duplicates" aria-live="polite"></div></details>');
 KoshReading.load().then(()=>{if(state.view==='library')renderLibraryResults();}).catch(error=>{const host=$('#reading-library-message');if(host)host.innerHTML=escapeHTML(error.message)+' <button class="text-button" data-reading-action="retry-state">Retry</button>';});
 readingUpdateLibrary();
}
function readingUpdateLibrary(){
 const host=$('#reading-resume'),message=$('#reading-library-message');if(!host)return;
 const data=readingModel.data;if(!data)return;const paused=typeof libraryBrowse!=='undefined'&&(libraryBrowse.busy||libraryBrowse.error||state.searchResults!==null);
 for(const element of $$('input,select,button',$('#reading-library-controls')))element.disabled=!!paused;
 if(message)message.textContent=paused?'Reading filters are paused while workspace passage results are shown.':'Reading filters apply to the source list. Tags and collection names match whole saved labels.';
 const resume=data.resume,doc=state.data.documents.find(d=>d.id===resume.document_id&&d.workspace_id===state.workspace),note=state.data.notes.find(n=>n.id===resume.note_id&&n.workspace_id===state.workspace);
 host.innerHTML=doc||note?'<section class="reading-resume"><div><strong>Continue '+escapeHTML(resume.view==='write'&&note?note.title||'Untitled note':doc?sourceLabel(doc):note.title||'Untitled note')+'</strong>'+(doc?'<p class="small muted">'+(doc.kind==='pdf'?'File page ':'Section ')+escapeHTML(resume.page)+(doc.archived?' · Archived source retained':'')+'</p>':'')+(resume.next_action?'<p>'+escapeHTML(resume.next_action)+'</p>':'<p class="muted small">Pick up where you last saved your place.</p>')+'</div>'+(doc?'<button class="button" data-reading-action="resume">Continue reading</button>':'')+(note?'<button class="button" data-reading-action="resume-draft">Continue draft</button>':'')+'</section>':'';
}
function readingDecorateLibraryRows(){
 if(state.view!=='library')return;for(const button of $$('[data-document]',$('#library-results'))){const doc=state.data.documents.find(d=>d.id===button.dataset.document);if(!doc)continue;const source=readingSource(doc.id),host=button.closest('.source-main');if(!host||$('.reading-source-labels',host))continue;
 host.insertAdjacentHTML('beforeend','<div class="reading-source-labels small">'+escapeHTML((source.favorite?'Favorite · ':'')+(readingStatuses.find(s=>s[0]===source.status)?.[1]||'Unread'))+(source.tags.length?' · '+source.tags.map(escapeHTML).join(', '):'')+(source.collection?' · '+escapeHTML(source.collection):'')+'</div>');}readingUpdateLibrary();
}
function readingMountReader(){
 readingResetWorkspace();readingModel.pageGeneration++;readingModel.geometry=null;const host=$('.reader-margin');if(!host||!state.doc)return;
 host.insertAdjacentHTML('beforeend','<section class="reading-tools" id="reading-tools" aria-label="Reading organization and saved passages"><details><summary>Reading place and organization</summary><form id="reading-source-form"><label>Reading state<select id="reading-source-status">'+readingStatusOptions('unread')+'</select></label><label class="reading-check"><input type="checkbox" id="reading-source-favorite"> Favorite source</label><label>Tags · comma separated<input id="reading-source-tags" maxlength="1000"></label><label>Collection<input id="reading-source-collection" maxlength="120"></label><label>Next action<input id="reading-next-action" maxlength="1000" placeholder="What will you do next?"></label><p class="muted small">Your page is remembered automatically. Save to keep changes to these fields.</p><button class="button" id="reading-save-place" type="submit" disabled>Save reading place and details</button></form></details><p id="reading-state-message" class="muted small" role="status">Loading saved reading state…</p><section id="reading-capture" aria-label="Capture selected passage"></section><details class="reading-annotations" open><summary>Saved passages <span id="reading-annotation-count"></span></summary><label class="reading-check"><input id="reading-show-archived" type="checkbox" '+(readingModel.showArchived?'checked':'')+'> Show archived passages</label><div id="reading-annotation-list" aria-live="polite"></div></details></section>');
 const target={workspace:state.workspace,document:state.doc.id,page:state.page,generation:readingModel.pageGeneration};
 for(const element of $$('input,select',$('#reading-source-form')))element.disabled=true;
 readingRenderCapture();KoshReading.load().then(()=>{if(!readingRequestCurrent(target,readingCurrentPage()))return;readingFillSourceForm();readingRenderAnnotations();readingRememberPage();}).catch(error=>{if(!readingRequestCurrent(target,readingCurrentPage()))return;$('#reading-state-message').innerHTML=escapeHTML(error.message)+' <button class="text-button" data-reading-action="retry-state">Retry</button>';});
}
function readingRememberPage(){
 clearTimeout(readingModel.progressTimer);const target=readingCurrentPage();
 readingModel.progressTimer=setTimeout(async()=>{if(state.view!=='read'||!readingRequestCurrent(target,readingCurrentPage())||!readingModel.data)return;const resume=readingModel.data.resume,source=readingSource(target.document);if(resume.document_id===target.document&&resume.page===target.page&&source.last_page===target.page&&resume.view==='read'&&resume.note_id===(state.note||null)&&resume.panel===readingVisiblePanel())return;
  try{if(source.last_page!==target.page)await KoshReading.mutate('/reading/source',{document_id:target.document,last_page:target.page});if(state.view==='read'&&readingRequestCurrent(target,readingCurrentPage())){const latest=KoshReading.current().resume;await KoshReading.mutate('/reading/resume',{document_id:target.document,page:target.page,view:'read',note_id:state.note||null,panel:readingVisiblePanel(),next_action:latest.document_id===target.document?latest.next_action:''});}}
  catch(error){if(readingRequestCurrent(target,readingCurrentPage())){const host=$('#reading-state-message');if(host)host.innerHTML='This page could not be remembered: '+escapeHTML(error.message)+' <button class="text-button" data-reading-action="remember-page">Retry</button>';}}
 },900);
}
function readingVisiblePanel(){return document.body.classList.contains('panel-open')?state.panel||'':'';}
function readingRestorePanel(resume){if(['ask','notes'].includes(resume.panel))state.panel=resume.panel;renderPanel();setPanelOpen(!!resume.panel);}
function readingRememberDraft(){
 readingResetWorkspace();clearTimeout(readingModel.progressTimer);if(state.view!=='write'||!state.note)return;const workspace=state.workspace,noteId=state.note,epoch=readingModel.epoch;
 readingModel.progressTimer=setTimeout(async()=>{if(state.workspace!==workspace||readingModel.epoch!==epoch||state.view!=='write'||state.note!==noteId)return;try{const data=await KoshReading.load(),panel=readingVisiblePanel();if(state.workspace!==workspace||readingModel.epoch!==epoch||state.view!=='write'||state.note!==noteId)return;if(data.resume.note_id===noteId&&data.resume.view==='write'&&data.resume.panel===panel)return;await KoshReading.mutate('/reading/resume',{note_id:noteId,view:'write',panel});}catch(error){notify('The last draft could not be remembered: '+error.message,true,true);}},900);
}
function readingCurrentPage(){return {workspace:state.workspace,document:state.doc?.id,page:state.page,generation:readingModel.pageGeneration};}
function readingFillSourceForm(){
 if(!$('#reading-source-form')||!state.doc||!readingModel.data)return;const source=readingSource(state.doc.id);
 const draft=readingPlaceDraft();$('#reading-source-status').value=draft?.status||source.status;$('#reading-source-favorite').checked=draft?draft.favorite:source.favorite;$('#reading-source-tags').value=draft?draft.tags:source.tags.join(', ');$('#reading-source-collection').value=draft?draft.collection:source.collection;$('#reading-next-action').value=draft?draft.next_action:readingModel.data.resume.document_id===state.doc.id?readingModel.data.resume.next_action:'';for(const element of $$('input,select',$('#reading-source-form')))element.disabled=false;$('#reading-save-place').disabled=false;$('#reading-state-message').textContent=draft?'Unsaved reading-place fields recovered. Save to retain them in the workspace.':'Original file stays unchanged. Reading place and annotations are separate local records.';
}
function readingRenderCapture(){
 const host=$('#reading-capture');if(!host||!state.doc)return;const draft=readingDraft();
 host.innerHTML='<h3>Capture a passage</h3><p class="muted small">'+(state.doc.kind==='pdf'&&state.readerMode==='page'?'Drag across words on the page image, then save a highlight and your comment.':'Select words in the extracted text, then save the exact quote and your comment.')+'</p>'+(draft.quote?'<blockquote class="reading-capture-quote">'+escapeHTML(draft.quote)+'</blockquote><label>Your comment<textarea id="reading-comment" rows="3" maxlength="8000">'+escapeHTML(draft.comment)+'</textarea></label><div class="reading-capture-actions"><button class="button primary" data-reading-action="save-annotation" '+(readingModel.busy?'disabled':'')+'>Save '+(state.doc.kind==='pdf'?'highlight':'passage')+'</button><button class="text-button" data-reading-action="clear-capture" '+(readingModel.busy?'disabled':'')+'>Discard capture draft</button></div><p id="reading-capture-message" class="muted small" role="status">Quote is preserved exactly; your comment is separate.</p>':'<p class="muted small">No passage selected. Image-only PDF pages need an OCR copy before word selection is available.</p>');
}
function readingRenderAnnotations(){
 const host=$('#reading-annotation-list');if(!host||!state.doc)return;readingRenderHighlights();if(host.contains(document.activeElement)&&document.activeElement.matches('[data-reading-comment-edit]'))return;const annotations=(readingModel.data?.annotations||[]).filter(a=>a.document_id===state.doc.id&&(readingModel.showArchived||!a.archived));
 $('#reading-annotation-count').textContent='('+annotations.length+')';host.innerHTML=annotations.length?annotations.map(annotation=>'<article class="reading-annotation"><button class="text-button" data-reading-jump="'+escapeHTML(annotation.id)+'">'+(state.doc.kind==='pdf'?'File page ':'Section ')+annotation.page+' · Go to passage</button>'+(annotation.archived?'<p class="small muted">Archived passage · retained</p>':'')+'<blockquote>'+escapeHTML(annotation.quote)+'</blockquote>'+(annotation.comment?'<p>'+escapeHTML(annotation.comment)+'</p>':'')+'<button class="button" data-reading-note="'+escapeHTML(annotation.id)+'">Create cited note</button><button class="text-button" data-reading-archive="'+escapeHTML(annotation.id)+'">'+(annotation.archived?'Restore passage':'Archive passage')+'</button><details><summary>Edit comment</summary><textarea rows="3" maxlength="8000" data-reading-comment-edit="'+escapeHTML(annotation.id)+'" aria-label="Comment on saved passage">'+escapeHTML(readingAnnotationComment(annotation))+'</textarea><button class="button" data-reading-save-comment="'+escapeHTML(annotation.id)+'">Save comment</button><p class="small muted">The exact quote and source locator stay unchanged.</p></details></article>').join(''):'<p class="muted small">Saved passages from this source will appear here.</p>';
}
function readingAnnotationComment(annotation){const key=state.workspace+':'+annotation.id;if(!readingModel.annotationEdits.has(key)){try{const saved=localStorage.getItem('kosh-reading-comment:'+key);if(saved!==null)readingModel.annotationEdits.set(key,saved);}catch{notify('Comment recovery could not be read. Existing storage was retained.',true,true);}}return readingModel.annotationEdits.has(key)?readingModel.annotationEdits.get(key):annotation.comment;}
function readingSetCapture(selection){
 if(!state.doc||!selection.quote)return;if(selection.quote.length>4000)return notify('Select a shorter passage, up to 4,000 characters.',true,true);const draft=readingDraft();if(readingModel.busy)return notify('Wait for the current passage save before selecting another quote.');
 if(draft.comment&&draft.quote!==selection.quote){notify('Save or discard the current commented passage before selecting a new quote.',true,true);return;}
 draft.quote=selection.quote;draft.word_indices=selection.word_indices||null;readingPreserveDraft();readingRenderCapture();
 if(typeof selectedPassage!=='undefined'){selectedPassage={document_id:state.doc.id,page:state.page,text:selection.quote};state.askScope='passage';if(typeof renderPanel==='function')renderPanel();if(typeof applyHints==='function')applyHints();}
}
function readingSelectionChanged(text){readingSetCapture({quote:String(text||''),word_indices:null});}
async function readingMountPageImage(documentId,page){
 const canvas=$('#reader-canvas'),image=canvas&&$('img',canvas);if(!image||state.doc?.id!==documentId||state.page!==page)return;
 const target=readingCurrentPage(),wrapper=document.createElement('div');wrapper.className='reading-page';image.replaceWith(wrapper);wrapper.appendChild(image);
 const message=document.createElement('p');message.className='reading-geometry-message muted small';message.textContent='Loading selectable PDF words…';canvas.prepend(message);
 try{const geometry=await request('/reading/geometry?workspace_id='+encodeURIComponent(state.workspace)+'&document_id='+encodeURIComponent(documentId)+'&page='+page);if(!readingRequestCurrent(target,readingCurrentPage())||!wrapper.isConnected)return;readingModel.geometry=geometry;
  const marks=document.createElement('div');marks.className='reading-highlight-layer';marks.setAttribute('aria-hidden','true');wrapper.appendChild(marks);
  const layer=document.createElement('div');layer.className='reading-word-layer';layer.setAttribute('aria-label','Selectable extracted PDF words');
  for(const word of geometry.words){const span=document.createElement('span');span.className='reading-word';span.dataset.readingWord=String(word.index);span.textContent=word.text+' ';readingPlaceRect(span,word.rect);span.style.fontSize=((word.rect[3]-word.rect[1])*(geometry.height/geometry.width)*100)+'cqw';layer.appendChild(span);}wrapper.appendChild(layer);
  message.textContent=geometry.words.length?'Select words over the original page image to capture a highlight.':'No extracted words on this page. Use an OCR copy or read the original image.';readingRenderHighlights();readingApplyPendingJump();
 }catch(error){if(readingRequestCurrent(target,readingCurrentPage())&&wrapper.isConnected){message.innerHTML='PDF word selection unavailable: '+escapeHTML(error.message)+' <button class="text-button" data-reading-action="retry-geometry">Retry</button>';}}
}
function readingPlaceRect(element,rect){element.style.left=(rect[0]*100)+'%';element.style.top=(rect[1]*100)+'%';element.style.width=((rect[2]-rect[0])*100)+'%';element.style.height=((rect[3]-rect[1])*100)+'%';}
function readingRenderHighlights(){
 const host=$('.reading-highlight-layer');if(!host||!state.doc)return;host.replaceChildren();for(const annotation of readingModel.data?.annotations||[]){if(annotation.document_id!==state.doc.id||annotation.page!==state.page||annotation.archived)continue;for(const rect of annotation.rects||[]){const mark=document.createElement('span');mark.className='reading-highlight';mark.dataset.readingHighlight=annotation.id;readingPlaceRect(mark,rect);host.appendChild(mark);}}readingApplyPendingJump();
}
function readingApplyPendingJump(){
 const annotation=readingModel.pendingJump;if(!annotation||annotation.document_id!==state.doc?.id||annotation.page!==state.page)return;
 const mark=$$('[data-reading-highlight]').find(element=>element.dataset.readingHighlight===annotation.id);if(mark){mark.scrollIntoView({block:'center',behavior:'auto'});mark.classList.add('reading-highlight-current');readingModel.pendingJump=null;return;}
 const text=$('.reader-text');if(text){const node=text.firstChild,index=node?.textContent.indexOf(annotation.quote);if(node&&index>=0){const range=document.createRange();range.setStart(node,index);range.setEnd(node,index+annotation.quote.length);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);text.scrollIntoView({block:'center'});notify('Saved quote selected in extracted text.');}else notify('Saved page opened. This exact quote could not be selected in the current extracted text.',true,true);readingModel.pendingJump=null;}
}
function readingBeforeNavigate(){return !readingModel.busy;}

document.addEventListener('input',event=>{if(event.target.hasAttribute('data-reading-comment-edit')){const key=state.workspace+':'+event.target.dataset.readingCommentEdit;readingModel.annotationEdits.set(key,event.target.value);try{localStorage.setItem('kosh-reading-comment:'+key,event.target.value);}catch{notify('Comment is kept in this window, but browser recovery could not be saved.',true,true);}}if(event.target.closest('#reading-source-form'))readingCapturePlaceForm();if(event.target.id==='reading-comment'){readingDraft().comment=event.target.value;readingPreserveDraft();}if(['reading-filter-tag','reading-filter-collection'].includes(event.target.id)&&!event.isComposing){readingModel.filter[event.target.id==='reading-filter-tag'?'tag':'collection']=event.target.value;renderLibraryResults();}});
document.addEventListener('compositionend',event=>{if(['reading-filter-tag','reading-filter-collection'].includes(event.target.id)){readingModel.filter[event.target.id==='reading-filter-tag'?'tag':'collection']=event.target.value;renderLibraryResults();}});
document.addEventListener('change',event=>{if(event.target.id==='reading-show-archived'){readingModel.showArchived=event.target.checked;readingRenderAnnotations();}if(event.target.closest('#reading-source-form'))readingCapturePlaceForm();if(event.target.id==='reading-filter-status'){readingModel.filter.status=event.target.value;renderLibraryResults();}if(event.target.id==='reading-filter-favorite'){readingModel.filter.favorite=event.target.checked;renderLibraryResults();}});
document.addEventListener('mouseup',event=>{
 if(state.view!=='read'||!state.doc)return;const layer=event.target.closest('.reading-word-layer');if(layer&&readingModel.geometry){const selection=window.getSelection();if(!selection?.rangeCount||selection.isCollapsed)return;const range=selection.getRangeAt(0),start=(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement).closest('[data-reading-word]'),end=(range.endContainer.nodeType===1?range.endContainer:range.endContainer.parentElement).closest('[data-reading-word]');if(!start||!end||!layer.contains(start)||!layer.contains(end))return;try{const result=readingSelectionFromWords(readingModel.geometry.words,Number(start.dataset.readingWord),Number(end.dataset.readingWord));readingSetCapture({quote:result.quote,word_indices:readingModel.geometry.words.filter(word=>word.index>=result.word_start&&word.index<=result.word_end).map(word=>word.index)});}catch(error){notify(error.message,true,true);}}
 else if(event.target.closest('.reader-text')){const selection=window.getSelection(),root=$('.reader-text');if(selection?.rangeCount&&root.contains(selection.anchorNode)&&root.contains(selection.focusNode))readingSelectionChanged(selection.toString());}
});
document.addEventListener('submit',async event=>{
 if(event.target.id!=='reading-source-form')return;event.preventDefault();if(readingModel.busy)return;const target=readingCurrentPage(),button=$('#reading-save-place');readingModel.busy=true;button.disabled=true;
 readingCapturePlaceForm();const draft=readingPlaceDraft(),snapshot=JSON.stringify(draft),draftKey=readingPlaceDraftKey(),fields={document_id:state.doc.id,status:draft.status,favorite:draft.favorite,tags:draft.tags.split(',').map(t=>t.trim()).filter(Boolean),collection:draft.collection,last_page:state.page},nextAction=draft.next_action;
 try{await KoshReading.mutate('/reading/source',fields);await KoshReading.mutate('/reading/resume',{document_id:fields.document_id,page:target.page,note_id:state.note||null,view:'read',panel:readingVisiblePanel(),next_action:nextAction});if(JSON.stringify(readingModel.placeDrafts.get(draftKey))===snapshot){readingModel.placeDrafts.delete(draftKey);try{localStorage.removeItem('kosh-reading-place:'+draftKey);}catch{notify('Reading place saved; browser recovery could not be cleared.',true,true);}}if(readingRequestCurrent(target,readingCurrentPage()))$('#reading-state-message').textContent='Reading place saved at '+(state.doc.kind==='pdf'?'file page ':'section ')+target.page+'.';}
 catch(error){if(readingRequestCurrent(target,readingCurrentPage()))$('#reading-state-message').textContent=error.message;notify(error.message,true,true);}finally{readingModel.busy=false;if(button.isConnected)button.disabled=false;}
});
document.addEventListener('click',async event=>{
 const action=event.target.closest('[data-reading-action]'),jump=event.target.closest('[data-reading-jump]'),note=event.target.closest('[data-reading-note]'),archive=event.target.closest('[data-reading-archive]'),saveComment=event.target.closest('[data-reading-save-comment]');if(!action&&!jump&&!note&&!archive&&!saveComment)return;
 try{
  if(archive||saveComment){if(readingModel.busy)return;const button=archive||saveComment,id=archive?archive.dataset.readingArchive:saveComment.dataset.readingSaveComment,annotation=readingModel.data.annotations.find(a=>a.id===id);if(!annotation)return;const key=state.workspace+':'+id,comment=readingAnnotationComment(annotation);readingModel.busy=true;button.disabled=true;try{await KoshReading.mutate('/reading/annotation',archive?{id,archived:!annotation.archived}:{id,comment});if(saveComment&&readingModel.annotationEdits.get(key)===comment){readingModel.annotationEdits.delete(key);try{localStorage.removeItem('kosh-reading-comment:'+key);}catch{notify('Comment saved, but browser recovery could not be cleared.',true,true);}}readingRenderAnnotations();notify(archive?(annotation.archived?'Passage restored.':'Passage archived; the record is retained.'):'Comment saved.');}finally{readingModel.busy=false;if(button.isConnected)button.disabled=false;}return;}
  if(jump){if(readingModel.busy)return notify('Wait for the reading save to finish.');const annotation=readingModel.data.annotations.find(a=>a.id===jump.dataset.readingJump);if(!annotation)return;readingModel.pendingJump=annotation;await openDocument(annotation.document_id,annotation.page,annotation.quote);readingApplyPendingJump();return;}
  if(note){if(readingModel.busy)return;const annotation=readingModel.data.annotations.find(a=>a.id===note.dataset.readingNote);if(annotation)await createNote('Passage from '+sourceLabel(state.doc),readingCitedBody(annotation));return;}
  const name=action.dataset.readingAction;
  if(name==='clear-filters'){readingModel.filter={status:'all',favorite:false,tag:'',collection:''};$('#reading-filter-status').value='all';$('#reading-filter-favorite').checked=false;$('#reading-filter-tag').value='';$('#reading-filter-collection').value='';renderLibraryResults();}
  else if(name==='resume'){if(readingModel.busy)return;const resume={...readingModel.data.resume};if(resume.document_id){await openDocument(resume.document_id,resume.page);if(state.view==='read'&&state.doc?.id===resume.document_id)readingRestorePanel(resume);}}
  else if(name==='resume-draft'){if(readingModel.busy)return;const resume={...readingModel.data.resume};if(resume.note_id){await selectNote(resume.note_id);if(state.view==='write'&&state.note===resume.note_id)readingRestorePanel(resume);}}
  else if(name==='retry-state'){await KoshReading.load(true);if(state.view==='read'){readingFillSourceForm();readingRenderAnnotations();}else renderLibraryResults();}
  else if(name==='remember-page')readingRememberPage();
  else if(name==='duplicates'){const workspace=state.workspace,host=$('#reading-duplicates');host.textContent='Comparing saved source metadata…';action.disabled=true;try{const result=await request('/reading/duplicates?workspace_id='+encodeURIComponent(workspace));if(state.workspace!==workspace||!host.isConnected)return;host.innerHTML='<p class="small muted">'+escapeHTML(result.notice)+'</p>'+(result.candidates.length?result.candidates.map(candidate=>'<article class="reading-duplicate-pair"><strong>Matching '+candidate.reasons.map(escapeHTML).join(' and ')+'</strong><div class="reading-duplicate-columns">'+candidate.document_ids.map(id=>{const doc=state.data.documents.find(d=>d.id===id);return doc?'<section><button class="text-button" data-document="'+escapeHTML(id)+'">'+escapeHTML(sourceLabel(doc))+'</button><p class="small muted">'+escapeHTML(doc.name)+' · '+escapeHTML(doc.kind)+(doc.archived?' · Archived':'')+'</p><p class="small">'+escapeHTML(doc.metadata?.authors||'Authors not entered')+' · '+escapeHTML(doc.metadata?.year||'Year not entered')+'</p><p class="small">'+escapeHTML(doc.metadata?.doi||'DOI not entered')+'</p><button class="text-button" data-metadata="'+escapeHTML(id)+'">Inspect source details</button></section>':'';}).join('')+'</div></article>').join(''):'<p class="small muted">No matching title or DOI candidates found in saved metadata.</p>');}catch(error){if(host.isConnected)host.textContent=error.message;throw error;}finally{if(action.isConnected)action.disabled=false;}}
  else if(name==='retry-geometry'){const image=$('#reader-canvas img');if(image){const canvas=$('#reader-canvas');canvas.replaceChildren(image);await readingMountPageImage(state.doc.id,state.page);}}
  else if(name==='clear-capture'){if(!readingModel.busy)readingDiscardDraft();}
  else if(name==='save-annotation'){
   if(readingModel.busy)return;const target=readingCurrentPage(),draft=readingDraft(),snapshot={...draft};if(!snapshot.quote)return;readingModel.busy=true;action.disabled=true;
   try{if(state.doc.kind==='pdf'&&!snapshot.word_indices){const geometry=readingModel.geometry||await request('/reading/geometry?workspace_id='+encodeURIComponent(target.workspace)+'&document_id='+encodeURIComponent(target.document)+'&page='+target.page);if(!readingRequestCurrent(target,readingCurrentPage()))throw new Error('Source page changed. Your capture draft is retained.');snapshot.word_indices=readingIndicesForQuote(geometry.words,snapshot.quote);}await KoshReading.mutate('/reading/annotation',{document_id:target.document,page:target.page,quote:snapshot.quote,comment:snapshot.comment,color:'yellow',...(snapshot.word_indices?{word_indices:snapshot.word_indices}:{})});if(readingRequestCurrent(target,readingCurrentPage())){if(draft.comment===snapshot.comment&&draft.quote===snapshot.quote)readingDiscardDraft();notify('Passage saved with its source locator.');}}
   finally{readingModel.busy=false;if(action.isConnected)action.disabled=false;}
  }
 }catch(error){const message=$('#reading-capture-message');if(message)message.textContent=error.message;notify(error.message,true,true);}
});
