'use strict';
// Network approval, transfer and executable installation are separate controls.
const KoshUpdater=(()=>{
 const qualifier='Download matches the SHA-256 published in the same GitHub release. This does not verify the publisher; installers are unsigned.';
 const phases={idle:'Updates are checked only when you ask.',checking:'Checking public releases…',available:'An update is available.',up_to_date:'No newer published version was found.',check_failed:'Release check failed. Retry when you are ready.',downloading:'Downloading and checking the published size and SHA-256…',downloaded:'Installer transfer check passed. Installation needs your approval.',download_failed:'Download failed. Retained partial files will not run.',awaiting_close:'The update worker is waiting. Close this Kosh window so its browser profile and service stop.',installing:'Installing into a new folder…',copying:'Copying saved data; the old copy stays intact.',starting:'Checking the new service and copied data…',retargeting:'Updating Kosh shortcuts after startup checks…',installed_verified:'New startup checked. Old installation and data are retained.',rolled_back:'Startup/action failed; old shortcuts were restored. Reopen the old Kosh shortcut.',rollback_failed:'Automatic recovery could not verify or newer work was detected. Both copies remain; review the receipt.',interrupted:'Update was interrupted. Retained files need review before a fresh attempt.',failed:'Update failed. Old data and candidate staging were retained.'};
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const pendingQualifier='A matching SHA-256 checks transfer integrity only. It does not verify the publisher; installers are unsigned.';
 const transferIdentity=value=>value?.job_id&&/^[a-f0-9]{64}$/.test(value.sha256||'')?value.job_id+':'+value.sha256+':'+(value.version||value.candidate?.version||''):'';
 let root=null,options=null,status=null,busy=false,busyAction='',error='',generation=0,accepted=false,approvedTransfer='',stopped=false;
 function render(){
  if(!root)return;
  const current=status||{phase:'idle'},candidate=current.candidate,identity=transferIdentity(current),allowInstall=accepted&&!!identity&&approvedTransfer===identity;
  const oldLive=root.querySelector('.update-status'),focused=root.ownerDocument?.activeElement;
  const focusSelector=focused&&typeof root.contains==='function'&&root.contains(focused)?focused.hasAttribute('data-update-unsigned')?'[data-update-unsigned]':focused.dataset.updateAction?'[data-update-action="'+focused.dataset.updateAction+'"]':null:null;
  const active=['awaiting_close','installing','copying','starting','retargeting'].includes(current.phase);
  root.innerHTML='<section class="kosh-updates" aria-labelledby="kosh-update-heading"><h3 id="kosh-update-heading">Kosh updates</h3><p class="small muted">Current version '+esc(current.current_version||'…')+'. Checking contacts the public needanotheremailid/kosh-desktop GitHub releases API. No library, notes or account information is sent.</p><p class="update-status" role="status" aria-live="polite">'+esc(error||current.message||phases[current.phase]||'Update status unavailable.')+'</p>'+(!current.install_supported?'<p class="small muted">In-app installation requires an installed Windows package. This source/development copy can check and download releases.</p>':'')+(candidate?'<div class="update-candidate"><strong>Version '+esc(candidate.version)+(candidate.prerelease?' · beta/prerelease':'')+'</strong><span>'+esc((candidate.size/1024/1024).toFixed(1))+' MB</span><a href="'+esc(candidate.release_url)+'" target="_blank" rel="noopener noreferrer">Release notes</a></div>':'')+'<p class="update-integrity small">'+qualifier+'</p><div class="update-controls"><button type="button" class="button" data-update-action="check" '+(busy||active?'disabled':'')+'>Check for updates</button>'+(current.phase==='available'?'<button type="button" class="button" data-update-action="download" '+(busy?'disabled':'')+'>Download installer and checksum</button>':'')+'</div>'+(current.phase==='downloaded'?'<div class="update-install"><label><input type="checkbox" data-update-unsigned '+(accepted?'checked':'')+'> I accept running an unsigned installer whose publisher identity is unverified.</label><p class="small muted">Install saves edits, stops Kosh, then waits for you to close this window. It installs into a new folder, copies saved data and browser recovery, checks startup, and updates shortcuts. The old installation and data stay intact.</p><button type="button" class="button primary" data-update-action="install" '+(busy||!accepted||!current.install_supported?'disabled':'')+'>Save, close and install</button></div>':'')+(current.sha256?'<details class="update-transfer"><summary>Transfer check</summary><p class="small">SHA-256 <code>'+esc(current.sha256)+'</code></p><p class="small">'+qualifier+'</p></details>':'')+(current.previous_update?'<details><summary>Previous update: '+esc(current.previous_update.phase)+'</summary><p class="small">'+esc(current.previous_update.message||phases[current.previous_update.phase]||'Receipt retained.')+'</p></details>':'')+(current.previous_installation?'<details class="update-previous"><summary>Previous installation retained</summary><p class="small">'+esc(current.previous_installation.install_path)+'</p><p class="small">Previous data: '+esc(current.previous_installation.data_path)+'</p><p class="small">Current data: '+esc(current.previous_installation.current_data_path)+'</p><p class="small">'+esc(current.previous_installation.warning)+'</p></details>':'')+'</section>';
  if(!identity)root.innerHTML=root.innerHTML.replace(qualifier,pendingQualifier);
  const install=root.querySelector('[data-update-action="install"]');if(install)install.disabled=busy||!allowInstall||!current.install_supported;
  if(current.resume_available)root.innerHTML=root.innerHTML.replace('</section>','<div class="update-install"><p class="small">Retained update needs an explicit resume or recovery. No new download is required.</p><label><input type="checkbox" data-update-resume '+(accepted?'checked':'')+'> I approve using the retained update and its unverified unsigned installer.</label><button type="button" class="button primary" data-update-action="resume" '+(busy||!accepted?'disabled':'')+'>Save, close and resume retained update</button></div></section>');
  if(current.activation_required)root.innerHTML=root.innerHTML.replace('</section>','<div class="update-install"><p class="small">This copy is waiting for its recorded startup checks. Finish opens it for editing and starts any enabled local backup schedule.</p><button type="button" class="button primary" data-update-action="activate" '+(busy?'disabled':'')+'>Finish opening this updated copy</button></div></section>');
  const live=root.querySelector('.update-status');
  if(live){live.textContent=error||(busyAction==='check'?'Checking public releases…':busyAction==='download'?'Downloading and checking size and SHA-256…':busyAction==='install'||busyAction==='resume'?'Saving edits and preparing update handoff…':current.message||phases[current.phase]||'Update status unavailable.');if(oldLive){oldLive.textContent=live.textContent;live.replaceWith(oldLive);}}
  for(const button of root.querySelectorAll('[data-update-action]'))button.addEventListener('click',()=>act(button.dataset.updateAction));
  const unsigned=root.querySelector('[data-update-unsigned]');if(unsigned)unsigned.addEventListener('change',()=>{accepted=unsigned.checked;approvedTransfer=accepted?identity:'';const button=root.querySelector('[data-update-action="install"]');if(button)button.disabled=busy||!accepted||!identity||!current.install_supported;});
  const resume=root.querySelector('[data-update-resume]');if(resume)resume.addEventListener('change',()=>{accepted=resume.checked;const button=root.querySelector('[data-update-action="resume"]');if(button)button.disabled=busy||!accepted;});
  if(focusSelector)root.querySelector(focusSelector)?.focus({preventScroll:true});
 }
 async function load(){const epoch=generation;try{const value=await options.request('/updates/status');if(epoch===generation){status=value;render();}}catch(problem){if(epoch===generation){error=problem.message;render();}}}
 async function act(action){
  if(busy||stopped)return;busy=true;busyAction=action;error='';if(action==='check'||action==='download'){accepted=false;approvedTransfer='';}render();
  try{
   if(action==='install'||action==='resume'){
    if(!accepted||(action==='install'&&(!transferIdentity(status)||approvedTransfer!==transferIdentity(status))))throw new Error('Accept the unsigned publisher status for this checked installer before installing.');
    if(typeof options.beforeInstall!=='function')throw new Error('Save/close integration is unavailable. Reopen Kosh before installing.');
    if(!await options.beforeInstall())return;
   }
   const body=action==='install'||action==='resume'?{approve:true,accept_unsigned:true}:action==='activate'?{}:{consent:true};
   const result=await options.request('/updates/'+action,body);
   status=action==='activate'?{...status,activation_required:false,phase:'installed_verified',message:'This updated copy is ready for editing. Old data remains retained.'}:result;
   if(action==='install'||action==='resume'){
    stopped=true;
    if(typeof options.afterInstall==='function')await options.afterInstall(status);
   }
  }catch(problem){error=problem.message||'Update action failed. Retained data remains available.';}
  finally{busy=false;busyAction='';render();}
 }
 return {qualifier,pendingQualifier,phases,mount(container,configuration){root=container;options=configuration;generation++;accepted=false;approvedTransfer='';error='';stopped=false;render();return load();},unmount(){root=null;generation++;},refresh:load};
})();
